
(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const el={file:$('#file'),drop:$('#drop'),fileInfo:$('#fileInfo'),status:$('#status'),sopList:$('#sopList'),preview:$('#preview'),detectBtn:$('#detectBtn'),applyBtn:$('#applyBtn'),allBtn:$('#allBtn'),noneBtn:$('#noneBtn'),exportBtn:$('#exportBtn')};
  let state={name:'',buf:null,model:null,parsed:null,keep:new Set(),working:null};
  const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
  const ptext=p=>(p&&Array.isArray(p.runs)?p.runs.map(r=>r.text||'').join(''):'').replace(/\s+/g,' ').trim();
  const setStatus=(s,k='')=>{el.status.textContent=s;el.status.className='status '+k};
  function rowsFrom(body,limit){let rows=[],cur=[];for(let i=0;i<Math.min(body.length,limit||body.length);i++){let p=body[i];if(p.kind==='cell'||p.kind==='rowEnd'){cur.push(i);if(p.kind==='rowEnd'){rows.push(cur);cur=[]}}else if(cur.length){cur=[]}}return rows;}
  function rowCells(body,row){return row.map(i=>ptext(body[i]));}
  function parseRange(s){let m=String(s||'').match(/(\d+)\s*(?:[-–—]\s*(\d+))?/);if(!m)return null;let a=+m[1],b=+(m[2]||m[1]);return {a,b,count:Math.max(1,b-a+1)}}
  function coreTitle(t){return norm(t).replace(/\bQUY TRINH\b/g,' ').replace(/\bKY THUAT\b/g,' ').replace(/\bSOP\b/g,' ').replace(/\s+/g,' ').trim();}
  function findTitleStart(body,title,from){let core=coreTitle(title), toks=core.split(' ').filter(x=>x.length>2);let key=toks.slice(-Math.min(5,toks.length)).join(' ');let best=-1;for(let i=from;i<body.length;i++){let w='';for(let j=i;j<Math.min(body.length,i+5);j++)w+=' '+norm(ptext(body[j]));if(key&&w.includes(key))return i;if(toks.length>=2){let hits=toks.filter(x=>w.includes(x)).length;if(hits>=Math.min(3,toks.length)&&best<0)best=i}}return best;}
  function analyse(model){const body=model.body||[];const rows=rowsFrom(body,Math.min(body.length,500));let toc=[];for(const row of rows){let c=rowCells(body,row);if(c.length<3)continue;let stt=parseInt((c[0]||'').match(/\d+/)?.[0]||'',10);let range=parseRange(c[c.length-1]);if(Number.isFinite(stt)&&range){toc.push({row,stt,title:c[1]||'',code:c.length>=4?c[2]:'',range,cells:c})}}
    if(!toc.length) throw new Error('Không nhận diện được bảng mục lục có STT và số trang.');
    let sopRows=toc.filter(x=>!norm(x.title).includes('MUC LUC'));
    let starts=[],from=Math.max(...toc.flatMap(x=>x.row))+1;
    for(const x of sopRows){let s=findTitleStart(body,x.title,from);if(s<0)s=from;starts.push(s);from=Math.max(s+1,from)}
    let sops=sopRows.map((x,i)=>({id:i,row:x.row,title:x.title||('SOP '+(i+1)),code:x.code,range:x.range,start:starts[i],end:i+1<starts.length?starts[i+1]:body.length}));
    return {toc,sops,body};
  }
  function cloneModel(m){return structuredClone(m)}
  function styleCopy(r){let o={};for(const k in r)if(k!=='text')o[k]=r[k];return o}
  function replaceRuns(runs,pairs){if(!Array.isArray(runs)||!runs.length)return runs;let text=runs.map(r=>r.text||'').join('');if(!text)return runs;let spans=[],off=0;for(let i=0;i<runs.length;i++){let t=runs[i].text||'';spans.push({s:off,e:off+t.length,r:runs[i]});off+=t.length}
    let reps=[];for(const [a,b] of pairs){if(!a||b==null)continue;let re=new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),m;while((m=re.exec(text))){reps.push({s:m.index,e:m.index+m[0].length,v:b});if(!m[0].length)re.lastIndex++}}
    reps.sort((a,b)=>a.s-b.s||b.e-a.e);let clean=[],last=-1;for(const r of reps){if(r.s>=last){clean.push(r);last=r.e}}if(!clean.length)return runs;
    let out=[],pos=0;function addOriginal(a,b){if(b<=a)return;for(const sp of spans){let s=Math.max(a,sp.s),e=Math.min(b,sp.e);if(e>s){let nr=styleCopy(sp.r);nr.text=text.slice(s,e);out.push(nr)}}}function styleAt(p){let sp=spans.find(x=>p>=x.s&&p<x.e)||spans[spans.length-1];return sp?styleCopy(sp.r):{}}
    for(const r of clean){addOriginal(pos,r.s);let nr=styleAt(r.s);nr.text=r.v;out.push(nr);pos=r.e}addOriginal(pos,text.length);return out.filter(r=>r.text!==''||Object.keys(r).length>1)
  }
  function deepReplace(v,pairs,seen=new WeakSet()){if(!v||typeof v!=='object'||v instanceof ArrayBuffer||ArrayBuffer.isView(v))return;if(seen.has(v))return;seen.add(v);if(Array.isArray(v.runs))v.runs=replaceRuns(v.runs,pairs);for(const k in v){if(k==='runs'||k==='images')continue;deepReplace(v[k],pairs,seen)}}
  function setParaText(p,text){if(!p.runs)p.runs=[];if(p.runs.length){p.runs[0].text=String(text);for(let i=1;i<p.runs.length;i++)p.runs[i].text=''}else p.runs=[{text:String(text)}]}
  function buildWorking(){if(!state.model||!state.parsed)return null;let m=cloneModel(state.model);let p=state.parsed;let body=m.body;let pairs=[[ $('#oldName').value.trim(),$('#newName').value.trim() ],[ $('#oldAddr').value.trim(),$('#newAddr').value.trim() ],[ $('#oldPerson').value.trim(),$('#newPerson').value.trim() ],[ $('#oldDate').value.trim(),$('#newDate').value.trim() ]].filter(x=>x[0]&&x[1]);deepReplace(m,pairs);
    const kept=p.sops.filter(s=>state.keep.has(s.id));let removeIdx=new Set();for(const s of p.sops)if(!state.keep.has(s.id)){for(let i=s.start;i<s.end;i++)removeIdx.add(i);for(const i of s.row)removeIdx.add(i)}
    let numericRows=p.toc.filter(x=>Number.isFinite(x.stt));let seq=1;let page=kept.length?kept[0].range.a:(p.sops[0]?.range.a||2);let keptMap=new Map(kept.map(s=>[s.id,s]));
    for(const tr of numericRows){let linked=p.sops.find(s=>s.row===tr.row);if(linked&&!state.keep.has(linked.id))continue;let row=tr.row; if(row[0]!=null)setParaText(body[row[0]],seq++);if(linked){let cnt=linked.range.count;let pg=cnt===1?String(page):`${page} - ${page+cnt-1}`;let last=row[row.length-1];setParaText(body[last],pg);page+=cnt}}
    m.body=body.filter((_,i)=>!removeIdx.has(i));state.working=m;renderPreview(kept);return m;
  }
  function renderSops(){let p=state.parsed;if(!p)return;el.sopList.innerHTML='';for(const s of p.sops){let d=document.createElement('label');d.className='sop';d.innerHTML=`<input type="checkbox" data-id="${s.id}" ${state.keep.has(s.id)?'checked':''}><div><div class="name">${escapeHtml(s.title)}</div><div class="meta">Ký hiệu: ${escapeHtml(s.code||'—')} · Trang gốc: ${s.range.a}${s.range.b!==s.range.a?'–'+s.range.b:''} · ${s.range.count} trang</div></div><span class="badge">SOP ${s.id+1}</span>`;el.sopList.appendChild(d)}$$('#sopList input').forEach(x=>x.addEventListener('change',e=>{let id=+e.target.dataset.id;e.target.checked?state.keep.add(id):state.keep.delete(id);buildWorking()}))}
  function renderPreview(kept){let rows=[],seq=1,page=state.parsed.sops[0]?.range.a||2;let muc=state.parsed.toc.find(x=>norm(x.title).includes('MUC LUC'));if(muc)rows.push([seq++,muc.title,muc.code||'',muc.range.a]);for(const s of kept){let pg=s.range.count===1?`${page}`:`${page}–${page+s.range.count-1}`;rows.push([seq++,s.title,s.code||'',pg]);page+=s.range.count}el.preview.innerHTML=`<table><thead><tr><th>STT</th><th>Tên SOP</th><th>Ký hiệu</th><th>Số trang</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${escapeHtml(String(c))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function suggestOld(){if(!state.model)return;let lines=(state.model.body||[]).map(ptext).filter(Boolean);let counts=new Map();for(let t of lines){let n=norm(t);if(/PHONG KHAM|NHA THUOC|QUAY THUOC|CONG TY/.test(n)&&t.length<120)counts.set(t,(counts.get(t)||0)+1)}let top=[...counts].sort((a,b)=>b[1]-a[1])[0];if(top)$('#oldName').value=top[0];setStatus(top?'Đã gợi ý tên cơ sở cũ.':'Chưa nhận diện được tên cơ sở tự động.',top?'ok':'')}
  async function openFile(file){try{if(!window.docToText||!window.textToDoc)throw new Error('Chưa tải được bộ xử lý .DOC. Hãy kiểm tra kết nối Internet rồi mở lại trang.');if(!/\.doc$/i.test(file.name))throw new Error('V1 hiện nhận file .DOC Word 97–2003.');setStatus('Đang đọc tài liệu…');let buf=await file.arrayBuffer();let model=docToText.model(buf);if(!model||!Array.isArray(model.body))throw new Error('Không đọc được file .DOC này (có thể file mã hóa/cũ/hỏng).');let parsed=analyse(model);state={name:file.name,buf,model,parsed,keep:new Set(parsed.sops.map(s=>s.id)),working:null};el.fileInfo.textContent=`${file.name} · ${(file.size/1024).toFixed(1)} KB · ${parsed.sops.length} SOP nhận diện`;['detectBtn','applyBtn','allBtn','noneBtn','exportBtn'].forEach(k=>el[k].disabled=false);renderSops();buildWorking();suggestOld();setStatus(`Đã nhận diện ${parsed.sops.length} SOP. Bỏ dấu tích ở SOP không cần.`, 'ok')}catch(e){console.error(e);setStatus(e.message||String(e),'err');alert(e.message||e)}}
  function save(){try{let m=buildWorking();if(!m)throw new Error('Chưa có tài liệu.');setStatus('Đang tạo file .DOC mới…');let bytes=textToDoc(m);let blob=new Blob([bytes],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.doc$/i,'')+'_DA_CHINH.doc';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500);setStatus('Đã xuất file mới. File gốc được giữ nguyên.','ok')}catch(e){console.error(e);setStatus('Xuất file lỗi: '+(e.message||e),'err');alert(e.message||e)}}
  el.drop.addEventListener('click',()=>el.file.click());el.file.addEventListener('change',()=>el.file.files[0]&&openFile(el.file.files[0]));['dragenter','dragover'].forEach(n=>el.drop.addEventListener(n,e=>{e.preventDefault();el.drop.classList.add('drag')}));['dragleave','drop'].forEach(n=>el.drop.addEventListener(n,e=>{e.preventDefault();el.drop.classList.remove('drag')}));el.drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&openFile(e.dataTransfer.files[0]));
  el.detectBtn.addEventListener('click',suggestOld);el.applyBtn.addEventListener('click',()=>{buildWorking();setStatus('Đã cập nhật bản xem trước.','ok')});el.allBtn.addEventListener('click',()=>{state.keep=new Set(state.parsed.sops.map(s=>s.id));renderSops();buildWorking()});el.noneBtn.addEventListener('click',()=>{if(confirm('Bỏ toàn bộ SOP khỏi tài liệu?')){state.keep.clear();renderSops();buildWorking()}});el.exportBtn.addEventListener('click',save);
  $$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.pane').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab+'Pane').classList.add('active')}));
  if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
